### ISSUE TITLE
Http request body in a trace is truncated to 512 bytes instead of 128 KB

### ISSUE THREAD

**Issue by shantanu-vsbhosale** [hypertrace/javaagent#288] opened 2021-03-16 18:13 UTC
**Use Case**
A spring pet clinic app (having POST service) was running which was instrumented by hypertrace java-agent. The app was loaded with multiple POST requests having body ~1MB.
hypertrace traces has the body of a http post request. By default it should capture 128 KB. 

**Issue**
We are only capturing 512 bytes of post request body. See attached images/files.

**Solution**
The post request body should be 128KB by default.
[input_1MB.txt](https://github.com/hypertrace/javaagent/files/6151347/input_1MB.txt)
<img width="1067" alt="post_request" src="https://user-images.githubusercontent.com/80242052/111359200-374c1b00-86b1-11eb-96b1-a9968d1300cb.png">
[output_512B.txt](https://github.com/hypertrace/javaagent/files/6151351/output_512B.txt)

**Comment by pavolloffay** [comment] 2021-07-06 12:42
Correct the default capture size is 128 KB. Which is `128*1024 = 131072 bytes`. One string character is `2 bytes`. Hence by default  `65536` characters should be captured.

**Comment by pavolloffay** [comment] 2021-07-06 13:22
I could not reproduce this issue with Jaeger and sample generated spring boot app.

Perhaps the collector or platform is tuncating the result.

**Comment by pavolloffay** [comment] 2021-07-06 13:26
Closing this as cannot reproduce

**Closed by pavolloffay** 2021-07-06 13:26 UTC
Labels: bug
